enum TWEEN_UPDATE_EVENT { BEGIN_STEP, STEP, END_STEP }

enum TWEEN_MODE 
{
	PERSIST, BACK_AND_PERSIST,
	ONE_SHOT, BACK_AND_SHOOT,
	LOOP, YOYO, RESTART
}

enum TWEEN_MODIFIER
{ 
	HORIZONTAL_POSITION, VERTICAL_POSITION, DIAGONAL_POSITION,
	WIDTH, HEIGHT, SIZE,
	OPACITY, COLOR, ANGLE, CUSTOM,
}

enum TWEEN_TIME_SOURCE { FRAMES, SECONDS, MILLISECONDS }